package com.teamscale.upload.xcode;

import java.io.File;

/** Utilities for converting Xcode coverage reports. */
public class ConversionUtils {
	/**
	 * File extension used for converted XCResult bundles.
	 */
	public static final String XCCOV_REPORT_FILE_EXTENSION = ".xccov";

	/**
	 * File extension used for xccov archives
	 *
	 * @see #isXccovArchive(File)
	 */
	public static final String XCCOV_ARCHIVE_FILE_EXTENSION = ".xccovarchive";

	/**
	 * File extension used for xcresult files
	 *
	 * @see #isXccovArchive(File)
	 */
	public static final String XCRESULT_FILE_EXTENSION = ".xcresult";

	/**
	 * Returns true if the file is a regular XCResult bundle directory indicated by
	 * the ".xcresult" ending in the directory name.
	 */
	public static boolean isXcresultBundle(File file) {
		return file.isDirectory() && file.getName().endsWith(XCRESULT_FILE_EXTENSION);
	}

	/**
	 * Returns true if the file is an xccov archive which is more compact than a
	 * regular XCResult bundle. An xccov archive can only be generated by XCode
	 * internal tooling but provides much better performance when extracting
	 * coverage. Note that xccov archives don't contain test results.
	 */
	public static boolean isXccovArchive(File file) {
		return file.isDirectory() && file.getName().endsWith(XCCOV_ARCHIVE_FILE_EXTENSION);
	}
}
